### ISSUE TITLE
Về hệ thống kết bạn

### ISSUE THREAD

**Issue by cd2012hn** [Natashi402/SimpleOnlineGameSE02#11]
Về cơ bản là vì mình có game có thể đối kháng được, t nghĩ mình có thể mở một hệ thống cho phép kết bạn và nhắn tin với bạn của mình, và khi mình muốn mời họ chơi, thì mình sẽ gửi đến một link vào room của game để họ vào có thể vào chơi được.

**Comment by Natashi402** [comment]
Về phần chat thì mình nghĩ nên làm một cái khung chat nhỏ fix ở phía trái dưới của trang web. Sẽ có lựa chọn kết bạn và tìm bạn theo tên đăng nhập hoặc email. Để làm được điều này chúng ta sẽ cần thêm 1 bảng bạn bè để kiểm soát việc kết bạn.

**Comment by Natashi402** [comment]
Ngoài ra thì còn cần thêm một hoặc hai bảng để lưu tin nhắn gửi cho nhau nữa

**Comment by cd2012hn** [comment]
tôi nghĩ rằng bạn bè sẽ là kết nối n-n, nên sẽ tạo một bảng lưu quan hệ, bạn(A,B) === bạn(B,A) <=> 2 record. Vậy thì bảng csdl friend sẽ gồm 2 phần: userId và friendId, mỗi quan hệ bạn bè tương ứng 2 record

**Comment by cd2012hn** [comment]
còn phần chat thì chắc chỉ cần một bảng duy nhất, có userId, friendId, msg và time. => ta có thể lưu được tin nhắn của người dùng gửi cho ai, vào thời gian nào => có thể sắp xếp và quản lý được

**Comment by nguyenthocongminh** [comment]
ô có định cho 2 người chưa đăng nhập nói chuyện với nhau không ?

**Comment by Natashi402** [comment]
Chưa đăng nhập thì mình ko có cái gì để kết nối lại hết cả thì tính sao bạn

**Comment by H3D-MinhNTC** [comment]
tôi đang nghĩ đến global chat room nhưng không biết nó có gây quá nhiều gánh nặng lên server k0 nhỉ

**Comment by nguyenthocongminh** [comment]
tôi đang nghĩ đến global chat room nhưng không biết nó có gây quá nhiều gánh nặng lên server k0 nhỉ

**Comment by cd2012hn** [comment]
vấn đề là thế này Minh ạ. những cái lõi mình chưa xong mà ông đã đòi làm cái hoàn thiện thì có khác gì bê tông cốt tre ở nơi cần bê tông cốt thép ko .-.

**Comment by cd2012hn** [comment]
ông ko cần phải cmt bằng tài khoản khác đâu, tài khoản nào chả được hả bạn?

**Comment by cd2012hn** [comment]
Đã hoàn thành
