### ISSUE TITLE
cách hoạt động của bảng relationship (hệ thống kết bạn)

### ISSUE THREAD

**Issue by nguyenthocongminh** [Natashi402/SimpleOnlineGameSE02#15]
mục tiêu của bài viết này là bàn về cách hoạt động của hệ thống kết bạn, mọi người cho ý kiến nhá

**Comment by nguyenthocongminh** [comment]
vấn đề ở đây mình vẫn chưa hiểu cơ chế hoạt động của bảng này lắm, mối quan hệ giữa user_id, other_id và status như thế nào

**Comment by cd2012hn** [comment]
@Natashi402 @nguyenthocongminh t sẽ giải thích luôn cho các bạn hiểu

- user_id là chủ thể, other_id là khách thể, status biểu thị quan hệ giữa chủ thể và khách thể

- status có 5 trạng thái:
0 là pending - đang duyệt, cụ thể là chờ được duyệt yêu cầu kết bạn
1 là accepted - đồng ý, tức là đã là bạn bè
2 là declined - từ chối, trong trạng thái này khách thể có thể gửi lại yêu cầu kết bạn cho chủ thể.
3 là blocked - chặn, chủ thể chặn khách thể, lúc này chủ thể chỉ có thể nhìn thấy khách thể ở trong danh sách blacklist, không gửi tin hay tìm kiếm được
4 là be blocked - bị chặn, chủ thể không thể tìm thấy khách thể, khách thể không hiện trong danh sách blacklist, không gửi được tin nhắn ( vì có phải bạn đâu .-.)
