### ISSUE TITLE
Lỗi hàm gửi yêu cầu kết bạn

### ISSUE THREAD

**Issue by nguyenthocongminh** [Natashi402/SimpleOnlineGameSE02#26]
![capture](https://user-images.githubusercontent.com/24455352/50784806-57b60900-12e1-11e9-980e-038ef83dd31c.PNG)

- Lỗi hàm gửi yêu cầu kết bạn

@cd2012hn

**Comment by cd2012hn** [comment]
t đã sửa xong r nhé, duyệt hộ t

**Comment by nguyenthocongminh** [comment]
#39 đã kiểm tra
